# Job Posting Analysis

In [1]:
# import os
import pandas as pd
%run utils.ipynb

## Load data

In [2]:
path = 'D:/Learn/projects/data/job_data/apify'
date = '01152025'
type = 'fin'
df0 = pd.read_csv(f'{path}/{date}_linkedin_{type}.csv')
print(df0.shape)
df0.head()

(688, 21)

,applicationsCount,applyType,applyUrl,benefits,companyId,companyName,companyUrl,contractType,description,experienceLevel,...,jobUrl,location,postedTime,posterFullName,posterProfileUrl,publishedAt,salary,sector,title,workType
0,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/financial-d...,401(k)\nDental insurance\nMedical insurance\nV...,1215629.0,Atlantic Group,https://www.linkedin.com/company/the-atlantic-...,Full-time,"Our Client, A top tier PE firm is looking to h...",Executive,...,https://www.linkedin.com/jobs/view/financial-d...,"New York, United States",9 hours ago,NaN,NaN,2025-01-16,"$200,000.00/yr - $250,000.00/yr",Staffing and Recruiting,"Financial Director, Private Equity",Accounting/Auditing and Finance
1,32 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/sr-manager-...,NaN,30086.0,Palo Alto Networks,https://www.linkedin.com/company/palo-alto-net...,Full-time,Our Mission\n\nAt Palo Alto Networks® everythi...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/sr-manager-...,"Santa Clara, CA",8 hours ago,NaN,NaN,2025-01-16,NaN,Computer and Network Security,Sr Manager of Strategic Finance,Finance
2,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,766746.0,"Piping Technology & Products, Inc.",https://www.linkedin.com/company/piping-techno...,Full-time,Company Overview\n\nPiping Technology & Produc...,Executive,...,https://www.linkedin.com/jobs/view/chief-finan...,"Houston, TX",10 hours ago,NaN,NaN,2025-01-16,NaN,IT Services and IT Consulting,Chief Financial Officer,Accounting/Auditing
3,50 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,Medical insurance\nVision insurance\nDental in...,5235.0,LHH,https://www.linkedin.com/company/lhhworldwide?...,Full-time,We are working with the CEO of a SaaS start-up...,Executive,...,https://www.linkedin.com/jobs/view/chief-finan...,New York City Metropolitan Area,13 hours ago,Allen Tsirinsky,https://www.linkedin.com/in/allen-tsirinsky-56...,2025-01-16,"$190,000.00/yr - $210,000.00/yr","Software Development and Technology, Informati...",Chief Financial Officer,Accounting/Auditing
4,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,40840.0,National Vision Inc.,https://www.linkedin.com/company/national-visi...,Full-time,Company Description\n\nNational Vision is one ...,Not Applicable,...,https://www.linkedin.com/jobs/view/chief-finan...,"Upland, CA",6 hours ago,NaN,NaN,2025-01-16,NaN,Retail,Chief Financial Officer,Human Resources

In [3]:
df0.sample(5).to_csv('test5.csv', index=False)
df0.sample(20).to_csv('test20.csv', index=False)
df0.sample(100).to_csv('test100.csv', index=False)

In [3]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   applicationsCount  688 non-null    object
 1   applyType          688 non-null    object
 2   applyUrl           688 non-null    object
 3   benefits           120 non-null    object
 4   companyId          682 non-null    float64
 5   companyName        682 non-null    object
 6   companyUrl         682 non-null    object
 7   contractType       688 non-null    object
 8   description        688 non-null    object
 9   experienceLevel    688 non-null    object
 10  id                 688 non-null    int64
 11  jobUrl             688 non-null    object
 12  location           688 non-null    object
 13  postedTime         688 non-null    object
 14  posterFullName     187 non-null    object
 15  posterProfileUrl   187 non-null    object
 16  publishedAt        688 non-null    object
 17  salary             271 non-null    object
 18  sector             682 non-null    object
 19  title              688 non-null    object
 20  workType           688 non-null    object
dtypes: float64(1), int64(1), object(19)
memory usage: 113.0+ KB

In [22]:
df0.head(3)

,applicationsCount,applyType,applyUrl,benefits,companyId,companyName,companyUrl,contractType,description,experienceLevel,...,jobUrl,location,postedTime,posterFullName,posterProfileUrl,publishedAt,salary,sector,title,workType
0,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/financial-d...,401(k)\nDental insurance\nMedical insurance\nV...,1215629.0,Atlantic Group,https://www.linkedin.com/company/the-atlantic-...,Full-time,"Our Client, A top tier PE firm is looking to h...",Executive,...,https://www.linkedin.com/jobs/view/financial-d...,"New York, United States",9 hours ago,NaN,NaN,2025-01-16,"$200,000.00/yr - $250,000.00/yr",Staffing and Recruiting,"Financial Director, Private Equity",Accounting/Auditing and Finance
1,32 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/sr-manager-...,NaN,30086.0,Palo Alto Networks,https://www.linkedin.com/company/palo-alto-net...,Full-time,Our Mission\n\nAt Palo Alto Networks® everythi...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/sr-manager-...,"Santa Clara, CA",8 hours ago,NaN,NaN,2025-01-16,NaN,Computer and Network Security,Sr Manager of Strategic Finance,Finance
2,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,766746.0,"Piping Technology & Products, Inc.",https://www.linkedin.com/company/piping-techno...,Full-time,Company Overview\n\nPiping Technology & Produc...,Executive,...,https://www.linkedin.com/jobs/view/chief-finan...,"Houston, TX",10 hours ago,NaN,NaN,2025-01-16,NaN,IT Services and IT Consulting,Chief Financial Officer,Accounting/Auditing

In [5]:
dupes = df0[df0.duplicated(subset=['applyUrl'], keep=False)]
print(dupes.shape)
dupes.head()

(44, 21)

,applicationsCount,applyType,applyUrl,benefits,companyId,companyName,companyUrl,contractType,description,experienceLevel,...,jobUrl,location,postedTime,posterFullName,posterProfileUrl,publishedAt,salary,sector,title,workType
18,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,52199182.0,Pop-Up Talent,https://www.linkedin.com/company/pop-uptalent?...,Full-time,"Chief Financial Officer\n\nPetaluma, CA 94954\...",Mid-Senior level,...,https://www.linkedin.com/jobs/view/chief-finan...,"Petaluma, CA",6 hours ago,M B.,https://www.linkedin.com/in/brionesmaria,2025-01-16,"$220,000.00/yr - $250,000.00/yr",Real Estate,Chief Financial Officer,Finance
19,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,52199182.0,Pop-Up Talent,https://www.linkedin.com/company/pop-uptalent?...,Full-time,"Chief Financial Officer\n\nPetaluma, CA 94954\...",Mid-Senior level,...,https://www.linkedin.com/jobs/view/chief-finan...,"Petaluma, CA",6 hours ago,M B.,https://www.linkedin.com/in/brionesmaria,2025-01-16,"$220,000.00/yr - $250,000.00/yr",Real Estate,Chief Financial Officer,Finance
96,Be among the first 25 applicants,EXTERNAL,https://eigx.fa.us6.oraclecloud.com/hcmUI/Cand...,NaN,23337.0,Sally Beauty,https://www.linkedin.com/company/sally-beauty-...,Full-time,Job Description\n\nEssential Function\n\nServe...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/sr-finance-...,"Denton, TX",11 hours ago,NaN,NaN,2025-01-16,NaN,Retail,SR FINANCE MANAGER,Finance and Sales
128,Be among the first 25 applicants,EXTERNAL,https://boards.greenhouse.io/robinhood/jobs/64...,NaN,3254263.0,Robinhood,https://www.linkedin.com/company/robinhood?trk...,Full-time,Join a leading fintech company that’s democrat...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/finance-str...,"New York, NY",6 hours ago,NaN,NaN,2025-01-16,NaN,Financial Services,"Finance & Strategy Senior Analyst, Crypto",Business Development and Sales
175,Be among the first 25 applicants,EXTERNAL,https://eigx.fa.us6.oraclecloud.com/hcmUI/Cand...,NaN,10250840.0,CosmoProf Beauty,https://www.linkedin.com/company/cosmoprof-bea...,Full-time,Job Description\n\nEssential Function\n\nServe...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/sr-finance-...,"Denton, TX",8 hours ago,NaN,NaN,2025-01-16,NaN,Retail,SR FINANCE MANAGER,Finance and Sales

In [38]:
df0[df0.duplicated(subset=['title','companyName','description'], keep=False)].shape

(73, 21)

In [36]:
df0[df0.duplicated(subset=['title','companyName','location','publishedAt'], keep=False)]

,applicationsCount,applyType,applyUrl,benefits,companyId,companyName,companyUrl,contractType,description,experienceLevel,...,jobUrl,location,postedTime,posterFullName,posterProfileUrl,publishedAt,salary,sector,title,workType
18,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,52199182.0,Pop-Up Talent,https://www.linkedin.com/company/pop-uptalent?...,Full-time,"Chief Financial Officer\n\nPetaluma, CA 94954\...",Mid-Senior level,...,https://www.linkedin.com/jobs/view/chief-finan...,"Petaluma, CA",6 hours ago,M B.,https://www.linkedin.com/in/brionesmaria,2025-01-16,"$220,000.00/yr - $250,000.00/yr",Real Estate,Chief Financial Officer,Finance
19,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,NaN,52199182.0,Pop-Up Talent,https://www.linkedin.com/company/pop-uptalent?...,Full-time,"Chief Financial Officer\n\nPetaluma, CA 94954\...",Mid-Senior level,...,https://www.linkedin.com/jobs/view/chief-finan...,"Petaluma, CA",6 hours ago,M B.,https://www.linkedin.com/in/brionesmaria,2025-01-16,"$220,000.00/yr - $250,000.00/yr",Real Estate,Chief Financial Officer,Finance
31,Be among the first 25 applicants,EXTERNAL,https://www.careerarc.com/job-listings/5110670...,NaN,27423.0,Republic National Distributing Company,https://www.linkedin.com/company/republic-nati...,Full-time,Republic National Distributing Company (RNDC) ...,Director,...,https://www.linkedin.com/jobs/view/director-bp...,"Atlanta, GA",13 hours ago,NaN,NaN,2025-01-16,NaN,Beverage Manufacturing,"Director, BPM - Portfolio & Finance",Finance and Sales
43,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,Medical insurance\nVision insurance\nDental in...,101394644.0,Encore Talent Solutions,https://www.linkedin.com/company/helloencore?t...,Full-time,Encore Talent is currently searching for a Chi...,Executive,...,https://www.linkedin.com/jobs/view/chief-finan...,"Cincinnati, OH",9 hours ago,NaN,NaN,2025-01-16,"$175,000.00/yr - $225,000.00/yr",Staffing and Recruiting,Chief Financial Officer,Accounting/Auditing and Finance
55,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,Medical insurance\nVision insurance\nDental in...,101394644.0,Encore Talent Solutions,https://www.linkedin.com/company/helloencore?t...,Full-time,Are you an experienced financial leader with a...,Executive,...,https://www.linkedin.com/jobs/view/chief-finan...,"Cincinnati, OH",8 hours ago,Randy Crenshaw,https://www.linkedin.com/in/randy-crenshaw-280...,2025-01-16,"$200,000.00/yr - $225,000.00/yr",Furniture and Home Furnishings Manufacturing,Chief Financial Officer,Finance
61,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/chief-finan...,Medical insurance\nVision insurance\nDental in...,101394644.0,Encore Talent Solutions,https://www.linkedin.com/company/helloencore?t...,Full-time,Are you an experienced financial leader with a...,Executive,...,https://www.linkedin.com/jobs/view/chief-finan...,"Cincinnati, OH",13 hours ago,Jake Hinkle,https://www.linkedin.com/in/jake-hinkle-263765226,2025-01-16,NaN,Financial Services,Chief Financial Officer,Finance
77,Be among the first 25 applicants,EXTERNAL,https://app.careerarc.com/job_postings/5964682...,NaN,27423.0,Republic National Distributing Company,https://www.linkedin.com/company/republic-nati...,Other,Republic National Distributing Company (RNDC) ...,Director,...,https://www.linkedin.com/jobs/view/director-bp...,"Atlanta, GA",13 hours ago,NaN,NaN,2025-01-16,NaN,Beverage Manufacturing,"Director, BPM - Portfolio & Finance",Finance and Sales
158,Be among the first 25 applicants,EXTERNAL,https://axos.wd5.myworkdayjobs.com/Axos/job/HQ...,NaN,18680857.0,Axos Bank,https://www.linkedin.com/company/axosbank?trk=...,Full-time,Axos Bank\n\nTarget Range:\n\n$27.00 - $33.86\...,Entry level,...,https://www.linkedin.com/jobs/view/jr-cre-anal...,"San Diego, CA",6 hours ago,NaN,NaN,2025-01-16,$27.00/hr - $33.86/hr,"Banking, Financial Services, and Investment Ba...",Jr. CRE Analyst,Business Development and Sales
167,Be among the first 25 applicants,EXTERNAL,https://axos.wd5.myworkdayjobs.com/Axos/job/HQ...,NaN,18680857.0,Axos Bank,https://www.linkedin.com/company/axosbank?trk=...,Full-time,Axos Bank\n\nTarget Range:\n\n$27.00 - $33.86\...,Entry level,...,https://www.linkedin.com/jobs/view/jr-cre-anal...,"San Diego, CA",6 hours ago,NaN,NaN,2025-01-16,$27.00/hr - $33.86/hr,"Banking, Financial Services, and Investment Ba...",Jr. CRE Analyst,Business Development and Sales
188,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-27\n\nJob Description\n\nRole Summary...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Alpharetta, GA",8 hours ago,NaN,NaN,2025-01-16,NaN,Financial Services,"VP, Treasury - Payments Product Manager",Other
229,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-3\n\nJob Description\n\nRole Summary/...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Altamonte Springs, FL",8 hours ago,NaN,NaN,2025-01-16,"$110,000.00/yr - $185,000.00/yr",Financial Services,"VP, Treasury - Payments Product Manager",Other
237,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-2\n\nJob Description\n\nRole Summary/...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Altamonte Springs, FL",8 hours ago,NaN,NaN,2025-01-16,"$110,000.00/yr - $185,000.00/yr",Financial Services,"VP, Treasury - Payments Product Manager",Other
243,Be among the first 25 applicants,EXTERNAL,https://www.careerarc.com/job-listings/5110671...,NaN,27423.0,Republic National Distributing Company,https://www.linkedin.com/company/republic-nati...,Full-time,Republic National Distributing Company (RNDC) ...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/manager-com...,"Sioux Falls, SD",13 hours ago,NaN,NaN,2025-01-16,NaN,Beverage Manufacturing,"Manager, Commercial Finance",Finance and Sales
264,Be among the first 25 applicants,EXTERNAL,https://app.careerarc.com/job_postings/5964691...,NaN,27423.0,Republic National Distributing Company,https://www.linkedin.com/company/republic-nati...,Other,Republic National Distributing Company (RNDC) ...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/manager-com...,"Sioux Falls, SD",13 hours ago,NaN,NaN,2025-01-16,NaN,Beverage Manufacturing,"Manager, Commercial Finance",Finance and Sales
270,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-1\n\nJob Description\n\nRole Summary/...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Alpharetta, GA",8 hours ago,NaN,NaN,2025-01-16,NaN,Financial Services,"VP, Treasury - Payments Product Manager",Other
273,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355\n\nJob Description\n\nRole Summary/Pu...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Alpharetta, GA",8 hours ago,NaN,NaN,2025-01-16,NaN,Financial Services,"VP, Treasury - Payments Product Manager",Other
296,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874357/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Seattle, WA",8 hours ago,NaN,NaN,2025-01-16,"$60,200.00/yr - $128,800.00/yr",IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
323,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-19\n\nJob Description\n\nRole Summary...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Draper, UT",8 hours ago,NaN,NaN,2025-01-16,NaN,Financial Services,"VP, Treasury - Payments Product Manager",Other
327,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-18\n\nJob Description\n\nRole Summary...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Draper, UT",8 hours ago,NaN,NaN,2025-01-16,"$110,000.00/yr - $185,000.00/yr",Financial Services,"VP, Treasury - Payments Product Manager",Other
353,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874371/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Dallas, TX",8 hours ago,NaN,NaN,2025-01-16,"$60,200.00/yr - $128,800.00/yr",IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
377,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-6\n\nJob Description\n\nRole Summary/...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Bentonville, AR",8 hours ago,NaN,NaN,2025-01-16,"$110,000.00/yr - $185,000.00/yr",Financial Services,"VP, Treasury - Payments Product Manager",Other
378,Be among the first 25 applicants,EXTERNAL,https://SynchronyFinancial.contacthr.com/14574...,NaN,3815936.0,Synchrony,https://www.linkedin.com/company/synchrony-fin...,Full-time,E2404355-5\n\nJob Description\n\nRole Summary/...,Not Applicable,...,https://www.linkedin.com/jobs/view/vp-treasury...,"Bentonville, AR",8 hours ago,NaN,NaN,2025-01-16,"$110,000.00/yr - $185,000.00/yr",Financial Services,"VP, Treasury - Payments Product Manager",Other
386,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874357/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Dallas, TX",8 hours ago,NaN,NaN,2025-01-16,NaN,IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
391,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874370/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Seattle, WA",8 hours ago,NaN,NaN,2025-01-16,"$60,200.00/yr - $128,800.00/yr",IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
436,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874371/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Arlington, VA",8 hours ago,NaN,NaN,2025-01-16,"$60,200.00/yr - $128,800.00/yr",IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
437,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874370/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Arlington, VA",8 hours ago,NaN,NaN,2025-01-16,"$60,200.00/yr - $128,800.00/yr",IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
454,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874371/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Seattle, WA",8 hours ago,NaN,NaN,2025-01-16,NaN,IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
486,33 applicants,EXTERNAL,https://Coca-Cola.contacthr.com/145752358,NaN,1694.0,The Coca-Cola Company,https://www.linkedin.com/company/the-coca-cola...,Full-time,The Coca-Cola’s Summer Internship program is a...,Not Applicable,...,https://www.linkedin.com/jobs/view/supply-chai...,"Atlanta, GA",6 hours ago,NaN,NaN,2025-01-16,NaN,"Manufacturing, Food and Beverage Manufacturing...",Supply Chain Strategy Intern,Other
545,Be among the first 25 applicants,EXTERNAL,https://www.amazon.jobs/jobs/2874357/senior-fi...,NaN,2382910.0,Amazon Web Services (AWS),https://www.linkedin.com/company/amazon-web-se...,Full-time,Description\n\nAmazon seeks a Senior Financial...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-fina...,"Arlington, VA",8 hours ago,NaN,NaN,2025-01-16,"$60,200.00/yr - $128,800.00/yr",IT Services and IT Consulting,"Senior Financial Analyst, AWS Support Finance","Finance, Information Technology, and Accountin..."
608,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/senior-acco...,NaN,61677.0,eTeam,https://www.linkedin.com/company/eteam?trk=pub...,Contract,Job Title: Senior Accountant\n\nLocation: Apop...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-acco...,"Apopka, FL",11 hours ago,Prabhat Pandey,https://in.linkedin.com/in/prabhat-pandey,2025-01-16,$32.00/hr - $34.00/hr,Food and Beverage Manufacturing,Senior Accountant,Accounting/Auditing
635,Be among the first 25 applicants,EASY_APPLY,https://www.linkedin.com/jobs/view/senior-acco...,NaN,61677.0,eTeam,https://www.linkedin.com/company/eteam?trk=pub...,Contract,Job Title: Senior Accountant\n\nLocation: Apop...,Mid-Senior level,...,https://www.linkedin.com/jobs/view/senior-acco...,"Apopka, FL",12 hours ago,Sharon Penukonda,https://in.linkedin.com/in/sharon-penukonda-71...,2025-01-16,NaN,Food and Beverage Manufacturing,Senior Accountant,Accounting/Auditing
682,Be among the first 25 applicants,EXTERNAL,https://Coca-Cola.contacthr.com/145750746,NaN,1694.0,The Coca-Cola Company,https://www.linkedin.com/company/the-coca-cola...,Full-time,The Coca-Cola’s Summer Internship program is a...,Not Applicable,...,https://www.linkedin.com/jobs/view/supply-chai...,"Atlanta, GA",6 hours ago,NaN,NaN,2025-01-16,NaN,"Manufacturing, Food and Beverage Manufacturing...",Supply Chain Strategy Intern,Other

In [39]:
df1 = df0.drop_duplicates(subset=['applyUrl'])
df1 = df1.drop_duplicates(subset=['title','companyName','description'])
df1 = df1.drop_duplicates(subset=['title','companyName','location','publishedAt'])
df1.shape

(624, 21)

In [40]:
cols_to_keep = ['title','companyName','salary','location','applyUrl','contractType','description',
       'experienceLevel','jobUrl','publishedAt','sector','workType','posterFullName','posterProfileUrl','companyId','companyUrl',]
df1 = df1[cols_to_keep]
print(df1.shape)
df1

(624, 16)

,title,companyName,salary,location,applyUrl,contractType,description,experienceLevel,jobUrl,publishedAt,sector,workType,posterFullName,posterProfileUrl,companyId,companyUrl
0,"Financial Director, Private Equity",Atlantic Group,"$200,000.00/yr - $250,000.00/yr","New York, United States",https://www.linkedin.com/jobs/view/financial-d...,Full-time,"Our Client, A top tier PE firm is looking to h...",Executive,https://www.linkedin.com/jobs/view/financial-d...,2025-01-16,Staffing and Recruiting,Accounting/Auditing and Finance,NaN,NaN,1215629.0,https://www.linkedin.com/company/the-atlantic-...
1,Sr Manager of Strategic Finance,Palo Alto Networks,NaN,"Santa Clara, CA",https://www.linkedin.com/jobs/view/sr-manager-...,Full-time,Our Mission\n\nAt Palo Alto Networks® everythi...,Mid-Senior level,https://www.linkedin.com/jobs/view/sr-manager-...,2025-01-16,Computer and Network Security,Finance,NaN,NaN,30086.0,https://www.linkedin.com/company/palo-alto-net...
2,Chief Financial Officer,"Piping Technology & Products, Inc.",NaN,"Houston, TX",https://www.linkedin.com/jobs/view/chief-finan...,Full-time,Company Overview\n\nPiping Technology & Produc...,Executive,https://www.linkedin.com/jobs/view/chief-finan...,2025-01-16,IT Services and IT Consulting,Accounting/Auditing,NaN,NaN,766746.0,https://www.linkedin.com/company/piping-techno...
3,Chief Financial Officer,LHH,"$190,000.00/yr - $210,000.00/yr",New York City Metropolitan Area,https://www.linkedin.com/jobs/view/chief-finan...,Full-time,We are working with the CEO of a SaaS start-up...,Executive,https://www.linkedin.com/jobs/view/chief-finan...,2025-01-16,"Software Development and Technology, Informati...",Accounting/Auditing,Allen Tsirinsky,https://www.linkedin.com/in/allen-tsirinsky-56...,5235.0,https://www.linkedin.com/company/lhhworldwide?...
4,Chief Financial Officer,National Vision Inc.,NaN,"Upland, CA",https://www.linkedin.com/jobs/view/chief-finan...,Full-time,Company Description\n\nNational Vision is one ...,Not Applicable,https://www.linkedin.com/jobs/view/chief-finan...,2025-01-16,Retail,Human Resources,NaN,NaN,40840.0,https://www.linkedin.com/company/national-visi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,VICE PRESIDENT - CORPORATE CREDIT,Job Juncture,"$175,000.00/yr - $195,000.00/yr","Chicago, IL",https://www.jobjuncture.com/all_jobs/24609/?ut...,Full-time,Job description: The VP - Credit Analyst will ...,Executive,https://www.linkedin.com/jobs/view/vice-presid...,2025-01-16,Staffing and Recruiting,Finance and Sales,Steve Kohn,https://www.linkedin.com/in/skohn1,3830959.0,https://www.linkedin.com/company/job-juncture?...
684,Project Accountant,Risus Talent Partners,"$95,000.00/yr - $110,000.00/yr",Greater Seattle Area,https://www.linkedin.com/jobs/view/project-acc...,Full-time,"Onsite role in Marysville, WA\n\n\n\n\nQualifi...",Not Applicable,https://www.linkedin.com/jobs/view/project-acc...,2025-01-16,Construction,Accounting/Auditing,Brooke Samios-Uy,https://www.linkedin.com/in/brooke-samios-uy-6...,80903120.0,https://www.linkedin.com/company/risus-talent-...
685,Accounting Manager - Real Estate,Hernandez Consulting & Construction,NaN,"New Orleans, LA",https://www.linkedin.com/jobs/view/accounting-...,Full-time,Accounting Manager – Real Estate\n\nYour New C...,Mid-Senior level,https://www.linkedin.com/jobs/view/accounting-...,2025-01-16,Internet Publishing,Sales and Management,NaN,NaN,9221215.0,https://www.linkedin.com/company/hernandez-con...
686,"Director, IT Finance",KPMG US,NaN,"Philadelphia, PA",https://www.kpmguscareers.com/jobdetail/?jobId...,Full-time,Known for being a great place to work and buil...,Director,https://www.linkedin.com/jobs/view/director-it...,2025-01-16,Financial Services,General Business,NaN,NaN,1079.0,https://www.linkedin.com/company/kpmg-us?trk=p...
687,Financial Director,Mountain Valley Developmental Services,"$86,320.00/yr - $111,280.00/yr","Glenwood Springs, CO",https://www.linkedin.com/jobs/view/financial-d...,Full-time,This position is IN-PERSON in Glenwood Springs...,Director,https://www.linkedin.com/jobs/view/financial-d...,2025-01-16,Health and Human Services,Finance and Sales,NaN,NaN,104789338.0,https://www.linkedin.com/company/mountain-vall...

## Exam and clean data for analysis
From here, some desired information have been extracted from the description and transformed to dataframe columns for further processing.

A closer look at the job titles reveals that some jobs are not in the united states, and not even written in English. This section exam them and decide whether they should be removed.

These posting with non-English titles and description are probably fake jobs or posted by poorly configured bots.
Some English titled posts are also shown because they contains non-ASC II characters.

In [41]:
# the funtion contains_non_english filter out job titles with non-English characters
df1[df1['title'].apply(contains_non_english)][['location', 'title']]

,location,title
178,"New York, United States",Business Management Analyst – Capital Structur...
359,"McLean, VA",Budget Analyst-Formulation – Senior SME
433,"Washington, DC",ISN/ECC – FMT Budget Analyst
506,"San Francisco, CA",PGIM Real Estate – Investment Analyst (San Fra...
576,"Atlanta, GA",2025 – Early Career – Innovation and Digital B...
610,"Mobile, AL",General Manager – US Manufacturing
634,"Melville, NY",Team Leader – Entry Level

In [42]:
# convert the non-ASC II characters to ASC II, also remove any non-printable characters.
# %run utils.ipynb
df = remove_non_english_jobs(df)
df[df['title'].apply(contains_non_english)][['location', 'title']]

Index(['title', 'companyName', 'salary', 'location', 'applyUrl',
       'contractType', 'description', 'experienceLevel', 'jobUrl',
       'publishedAt', 'sector', 'workType', 'posterFullName',
       'posterProfileUrl', 'companyId', 'companyUrl'],
      dtype='object')

Empty DataFrame
Columns: [location, title]
Index: []

In [44]:
# re-check job titles
df['title'].value_counts()[:20]

title
Chief Financial Officer                                      21
Financial Analyst                                            18
Senior Financial Analyst                                     17
Controller                                                   16
Senior Accountant                                            15
VP, Treasury - Payments Product Manager                      14
Accounting Manager                                           13
Financial Controller                                         10
Finance Manager                                               8
Executive Assistant (Remote - OPEN TO ALL U.S. LOCATIONS)     7
Assistant Controller                                          7
Director of Finance                                           7
Regional Director of Operations                               7
Senior Investment Associate                                   5
Accounts Payable Specialist                                   5
Finance Director                                              4
Senior Controller                                             4
General Manager                                               4
Investment Analyst                                            4
Project Manager                                               3
Name: count, dtype: int64

In [45]:
# exam the company names
df['companyName'].value_counts()[:20]

companyName
Synchrony                                 14
Amazon                                    10
Republic National Distributing Company     9
Robert Half                                8
High Country: Private Equity Search        7
Alvarez & Marsal                           7
iHire                                      6
MedMark Treatment Centers                  6
Jobot                                      6
Amazon Web Services (AWS)                  5
The Coca-Cola Company                      5
Vaco                                       5
Kforce Inc                                 4
Selby Jennings                             4
OWEN ELECTRIC COMPANY, INC.                4
Encore Talent Solutions                    4
LHH                                        4
Insight Global                             3
Atlantic Group                             3
JCW                                        3
Name: count, dtype: int64

In [16]:
# extract unique company list
company_names = df['companyName'].unique()
with open ('company_names.txt', 'w') as file:
    for val in company_names:
        file.write(str(val) + '\n')
# ask ChatGPT what companies are suspicious, the result is saved in the file called

In [46]:
# noname_company = df[df['companyName'].isna()]
# noname_company.to_csv('noname_company.csv')

In [ ]:
# check some company names
# companyname_to_look = ['High Country: Private Equity Search','iHire','Jobot','Encore Talent Solutions','LHH','Insight Global','Atlantic Group','JCW']
# cols_to_keep2 = ['title', 'companyName','contractType', 'experienceLevel', 'jobUrl',
#      'posterFullName','companyUrl']
# company_sus = df1[df1['companyName'].isin(companyname_to_look)][cols_to_keep2].copy()
# company_sus.to_csv('company_sus.csv')

In [48]:
df.to_csv(f'{path}/{date}_linkedin_{type}_cleaned.csv', index=False)